### ISSUE TITLE
A freshman can not find the module named 'SocialBehaviorAtlas.train_utils.yolact.sbea_train'

### ISSUE THREAD

**Issue by wangyuxiepython** [YNCris/SBeA_release#8]
Hi,I am grateful that you open sourced you code,but I encountered a error that I can't resolve while following the README_SBeA_tracker.So,may I ask if you can give me some suggestions?
This is the  Traceback:
Traceback (most recent call last):
  File "D:\Sbea\SBeA_release\SBeA_tracker\SBeA-Windows-main\gui\main.py", line 1, in <module>
    from tab import MainWindow
  File "gui\tab.py", line 1, in init tab
  File "gui\eval.py", line 7, in init eval
  File "D:\Sbea\SBeA_release\SBeA_tracker\SBeA-Windows-main\SocialBehaviorAtlas\__init__.py", line 5, in <module>
    from SocialBehaviorAtlas.train_seg_models import train_seg_models
  File "SocialBehaviorAtlas\train_seg_models.py", line 15, in init train_seg_models
  File "D:\Sbea\SBeA_release\SBeA_tracker\SBeA-Windows-main\SocialBehaviorAtlas\train_utils\__init__.py", line 2, in <module>
    from SocialBehaviorAtlas.train_utils.train_yolact import train_yolact
  File "SocialBehaviorAtlas\train_utils\train_yolact.py", line 9, in init train_yolact
  File "D:\Sbea\SBeA_release\SBeA_tracker\SBeA-Windows-main\SocialBehaviorAtlas\train_utils\yolact\__init__.py", line 1, in <module>
    from SocialBehaviorAtlas.train_utils.yolact.sbea_train import sbea_train
ModuleNotFoundError: No module named 'SocialBehaviorAtlas.train_utils.yolact.sbea_train'

**Comment by YNCris** [comment]
Hi! Thank you for trying our SBeA! This is a common problem which may be caused by the file synchronization problem of GitHub. I attached a link containing our codes. You can find it at the last of README_SBeA_tracker. I also attached the link here "https://drive.google.com/file/d/1B7BWCUgwUnZdWeP4_rv_2byKJ22qZ4tY/view". Feel free to ask further questions if it does not work!

**Comment by wangyuxiepython** [comment]
Thank you for your response and your help !
